### ISSUE TITLE
After running npm install and then ng new, It says teams-angular collection not found

### ISSUE THREAD

**Issue by samargy** [sinedied/teams-angular#18]
command:  ng new teams-app --collection teams-angular 

Output: An unhandled exception occurred: Collection "teams-angular" cannot be resolved.
See "/tmp/ng-VFFe60/angular-errors.log" for further details.

**Comment by sinedied** [comment]
Hi! Did you run the command `npm install -g teams-angular` before trying to use the collection?

**Comment by joelhaugen** [comment]
I am having the exact same issue.  Yes, I did run the command npm install -g teams-angular.

**Comment by sinedied** [comment]
Could you give more details about your configuration? Like OS/Version, Node and npm version, how you installed Node (NVM or other) and the content of your `angular-errors.log` file?

**Comment by samargy** [comment]
Clean install of npm appeared to fix the problem.

**Comment by isinadinos** [comment]
I am having same issue and clean install of npm didn't help.

I am using windows 10 with node 14.17.6 and npm 6.14.15 and also tried with node 16.14.0 and npm 8.5.5 (using the nvm 1.1.9)

[```
error] Error: Collection "teams-angular" cannot be resolved.
    at SchematicEngineHost.resolve (C:\Users\i.sinadinos\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:75:19)
    at SchematicEngineHost._resolveCollectionPath (C:\Users\i.sinadinos\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\node-module-engine-host.js:80:37)
    at SchematicEngineHost.createCollectionDescription (C:\Users\i.sinadinos\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\tools\file-system-engine-host-base.js:118:27)
    at SchematicEngine._createCollectionDescription (C:\Users\i.sinadinos\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:162:40)
    at SchematicEngine.createCollection (C:\Users\i.sinadinos\AppData\Roaming\npm\node_modules\@angular\cli\node_modules\@angular-devkit\schematics\src\engine\engine.js:155:43)
    at NewCommand.getCollection (C:\Users\i.sinadinos\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:147:35)
    at NewCommand.initialize (C:\Users\i.sinadinos\AppData\Roaming\npm\node_modules\@angular\cli\models\schematic-command.js:66:37)
    at async NewCommand.validateAndRun (C:\Users\i.sinadinos\AppData\Roaming\npm\node_modules\@angular\cli\models\command.js:121:22)
    at async runCommand (C:\Users\i.sinadinos\AppData\Roaming\npm\node_modules\@angular\cli\models\command-runner.js:228:24)
    at async default_1 (C:\Users\i.sinadinos\AppData\Roaming\npm\node_modules\@angular\cli\lib\cli\index.js:70:31)
```

**Comment by sinedied** [comment]
I added a note in the readme regarding this issue.
If you're having the same error, please try running these commands:

```sh
npm uninstall -g @angular/cli teams-angular
npm cache clean --force
npm install -g npm@latest
npm install -g @angular/cli teams-angular
```
