### ISSUE TITLE
Can not sign in with microsoft

### ISSUE THREAD

**Issue by isinadinos** [sinedied/teams-angular#20]
After clicking the button "sign in with microsoft " I get an error in console and can't procced:

```
ERROR Error: Uncaught (in promise): BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
BrowserAuthError: interaction_in_progress: Interaction is currently in progress. Please ensure that this interaction has been completed before calling an interactive API.  For more visit: aka.ms/msaljs/browser-errors.
    at BrowserAuthError.AuthError [as constructor] (AuthError.js:31:24)
    at new BrowserAuthError (BrowserAuthError.js:201:28)
    at BrowserAuthError.createInteractionInProgressError (BrowserAuthError.js:268:16)
    at BrowserCacheManager.setInteractionInProgress (BrowserCacheManager.js:1187:23)
    at ClientApplication.preflightInteractiveRequest (ClientApplication.js:847:33)
    at ClientApplication.preflightBrowserEnvironmentCheck (ClientApplication.js:832:18)
    at PublicClientApplication.<anonymous> (ClientApplication.js:226:22)
    at step (_tslib.js:87:23)
    at Object.next (_tslib.js:68:53)
    at _tslib.js:61:71
    at resolvePromise (zone.js:1214:31)
    at resolvePromise (zone.js:1168:17)
    at zone.js:1121:17
    at zone.js:1137:33
    at step (_tslib.js:60:47)
    at _tslib.js:61:9
    at new ZoneAwarePromise (zone.js:1432:21)
    at __awaiter (_tslib.js:57:12)
    at PublicClientApplication.loginRedirect (PublicClientApplication.js:62:25)
    at MsalService.loginRedirect (azure-msal-angular.js:58:35)
```

It this normal when running app in pc? Or it is designed to work only inside ms teams?

**Comment by sinedied** [comment]
@waldekmastykarz can you help here?

**Comment by waldekmastykarz** [comment]
This can indicate, that the previous sign in process got stuck/broke and the current browser session still thinks that singing in is in progress. If you clear local storage, you should be able to sign in as intended.

**Comment by isinadinos** [comment]
Confirmed that when deleted the local storage, then logged in successfully. This happens many times while testing but is solved everytime local storage is deleted. Thank you @waldekmastykarz.

**Comment by waldekmastykarz** [comment]
Thanks to let us know that you've got unblocked @isinadinos 👍
